PENDING_STAGES: frozenset[str] = frozenset({
    'AudioExtractBgStage', 'AudioExtractVocalStage',
    'DirectorTimelineStage', 'TimelineVideoStage',
    'ShotImagesStage', 'StoryboardStage',
    'VideoSubtitleSelectEraseStage', 'VideoSubtitleSmartEraseStage',
    'VideoUpscaleStage',
})

NON_STAGE_NODES: frozenset[str] = frozenset({'MaskCleanup', 'MakeProxyStage'})

STAGE_META: dict[str, dict] = {
    'ProjectStage':                 {'kind': 'project'},
    'TextStage':                    {'kind': 'text',         'workflow_kind': 'text'},
    'ImageStage':                   {'kind': 'image-batch',  'workflow_kind': 'image'},
    'VideoStage':                   {'kind': 'video',        'workflow_kind': 'video'},
    'H3VideoStage':                 {'kind': 'video',        'workflow_kind': 'video'},
    'DirectorStage':                {'kind': 'video',        'workflow_kind': 'video'},
    'AudioStage':                   {'kind': 'audio',        'workflow_kind': 'audio'},
    'SpeechStage':                  {'kind': 'audio',        'workflow_kind': 'speech'},
    'ImagePickerStage':             {'kind': 'image-picker'},
    'AudioPickerStage':             {'kind': 'audio-picker'},
    'VideoPickerStage':             {'kind': 'video-picker'},
    'ShotImagesStage':              {'kind': 'image-batch',  'workflow_kind': 'shot-images'},
    'UpscaleStage':                 {'kind': 'image',        'workflow_kind': 'upscale'},
    'OutpaintStage':                {'kind': 'image',        'workflow_kind': 'outpaint'},
    'InpaintStage':                 {'kind': 'image',        'workflow_kind': 'inpaint'},
    'ImageEditStage':               {'kind': 'image',        'workflow_kind': 'image-edit'},
    'BridgeToText':                 {'kind': 'text'},
    'BridgeToImage':                {'kind': 'image'},
    'BridgeToImages':               {'kind': 'image-batch'},
    'BridgeToVideo':                {'kind': 'video'},
    'BridgeToAudio':                {'kind': 'audio'},
    'EraseStage':                   {'kind': 'image',        'workflow_kind': 'erase'},
    'CutoutStage':                  {'kind': 'image',        'workflow_kind': 'cutout'},
    'SplitPartStage':               {'kind': 'image-batch',  'workflow_kind': 'split-part'},
    'CropStage':                    {'kind': 'image',       'variant': 'transform'},
    'RotateStage':                  {'kind': 'image',       'variant': 'transform'},
    'MirrorStage':                  {'kind': 'image',       'variant': 'transform'},
    'ColorGradeStage':              {'kind': 'image',       'variant': 'transform'},
    'CompareStage':                 {'kind': 'image',       'variant': 'transform'},
    'GridSplitStage':               {'kind': 'image-batch', 'variant': 'transform'},
    'DirectorTimelineStage':        {'kind': 'timeline',    'variant': 'transform'},
    'TimelineVideoStage':           {'kind': 'video',        'workflow_kind': 'timeline'},
    'ImageVariationsStage':         {'kind': 'image-batch',  'workflow_kind': 'multiview',
                                     'workflow_kinds': ['multiview', 'sequence']},
    'RelightStage':                 {'kind': 'image',       'variant': 'loader'},
    'MultiangleStage':              {'kind': 'image',        'workflow_kind': 'multiangle'},
    'VideoExtractFrameStage':       {'kind': 'image'},
    'VideoClipStage':               {'kind': 'video'},
    'VideoCropStage':               {'kind': 'video'},
    'VideoConcatStage':             {'kind': 'video'},
    'VideoSpeedStage':              {'kind': 'video'},
    'VideoRotateStage':             {'kind': 'video'},
    'VideoSplitStage':              {'kind': 'video'},
    'VideoVolumeStage':             {'kind': 'video'},
    'VideoMuxAudioStage':           {'kind': 'video'},
    'VideoFramesStage':             {'kind': 'image-batch'},
    'VideoResizeStage':             {'kind': 'video'},
    'VideoUpscaleStage':            {'kind': 'video',        'workflow_kind': 'upscale'},
    'VideoSubtitleSmartEraseStage': {'kind': 'video'},
    'VideoSubtitleSelectEraseStage':{'kind': 'video'},
    'AudioExtractVocalStage':       {'kind': 'audio',        'workflow_kind': 'audio-vocal'},
    'AudioExtractBgStage':          {'kind': 'audio',        'workflow_kind': 'audio-bg'},
    'AudioVideoDemuxAudioStage':    {'kind': 'audio'},
    'AudioVideoDemuxVideoStage':    {'kind': 'video'},
    'VideoColorStage':              {'kind': 'video'},
    'VideoCurvesStage':             {'kind': 'video'},
    'VideoLUTStage':                {'kind': 'video'},
    'VideoBlurSharpenStage':        {'kind': 'video'},
    'VideoDenoiseStage':            {'kind': 'video'},
    'VideoChromaKeyStage':          {'kind': 'video'},
    'VideoTransitionStage':         {'kind': 'video'},
    'VideoLumaWipeStage':           {'kind': 'video'},
    'VideoStabilizeStage':          {'kind': 'video'},
    'SceneDetectStage':             {'kind': 'image-batch'},
    'VideoInterpolateStage':        {'kind': 'video'},
    'VideoDeinterlaceStage':        {'kind': 'video'},
    'VideoStylizeStage':            {'kind': 'video'},
    'VideoScopesStage':             {'kind': 'image'},
    'FXChainStage':                 {'kind': 'video'},
    'AudioDynamicsStage':           {'kind': 'audio'},
    'AudioEQStage':                 {'kind': 'audio'},
    'AudioLoudnessStage':           {'kind': 'audio'},
    'AudioDenoiseStage':            {'kind': 'audio'},
    'AudioEchoStage':               {'kind': 'audio'},
    'AudioModulationStage':         {'kind': 'audio'},
    'AudioStereoStage':             {'kind': 'audio'},
    'AudioTimePitchStage':          {'kind': 'audio'},
    'AudioRepairStage':             {'kind': 'audio'},
    'AudioSaturateStage':           {'kind': 'audio'},
    'AudioCrossfadeStage':          {'kind': 'audio'},
    'AudioAnalyzeStage':            {'kind': 'text'},
    'AudioVisualizeStage':          {'kind': 'image'},
    'AudioMixStage':                {'kind': 'audio'},
    'AudioSegmentExportStage':      {'kind': 'text'},
    'AudioClipStage':               {'kind': 'audio'},
    'AudioSplitStage':              {'kind': 'audio'},
    'AudioConvolveStage':           {'kind': 'audio'},
    'AudioSweepStage':              {'kind': 'audio'},
    'AudioDeconvolveStage':         {'kind': 'audio'},
    'VideoCompositeStage':          {'kind': 'video'},
    'VideoTransformStage':          {'kind': 'video'},
    'CornerPinStage':               {'kind': 'video'},
    'RotoMaskStage':                {'kind': 'video'},
    'MotionTrackStage':             {'kind': 'text'},
    'TitleStage':                   {'kind': 'video'},
    'SubtitleStage':                {'kind': 'video'},
    'TimeRemapStage':               {'kind': 'video'},
    'SequenceStage':                {'kind': 'video'},
    'VideoStabilizeV2Stage':        {'kind': 'video'},
    'PaintStrokeStage':             {'kind': 'video'},
    'STMapStage':                   {'kind': 'video'},
    'MaskPropagateStage':           {'kind': 'video'},
    'SubtitleGenStage':             {'kind': 'text', 'workflow_kind': 'speech-to-text'},
    'HueCorrectStage':              {'kind': 'video'},
    'GlowStage':                    {'kind': 'video'},
    'GodRaysStage':                 {'kind': 'video'},
    'PatternStage':                 {'kind': 'video'},
    'PIKStage':                     {'kind': 'video'},
    'KeyerStage':                   {'kind': 'video'},
    'DespillStage':                 {'kind': 'video'},
    'ColorSuppressStage':           {'kind': 'video'},
    'KeyMixStage':                  {'kind': 'video'},
    'MatteMonitorStage':            {'kind': 'video'},
    'MatteMorphStage':              {'kind': 'video'},
    'FrameBlendStage':              {'kind': 'video'},
    'SelectiveColorStage':          {'kind': 'video'},
    'ChromaShiftStage':             {'kind': 'video'},
    'PseudocolorStage':             {'kind': 'video'},
    'PosterizeStage':               {'kind': 'video'},
    'GrayWorldStage':               {'kind': 'video'},
    'CDLStage':                     {'kind': 'video'},
    'ShapeMaskStage':               {'kind': 'video'},
    'LensDistortStage':             {'kind': 'video'},
    'ChromaticAberrationStage':     {'kind': 'video'},
    'LensFlareStage':               {'kind': 'video'},
    'ZDefocusStage':                {'kind': 'video'},
    'FaceBlurStage':                {'kind': 'video'},
    'SpotRemoverStage':             {'kind': 'video'},
    'ParticlesStage':               {'kind': 'video'},
    'HistogramEqStage':             {'kind': 'video'},
    'Video360Stage':                {'kind': 'video'},
    'AudioDuckStage':               {'kind': 'audio'},
    'AudioStemSplitStage':          {'kind': 'audio'},
    'AudioNoiseReductionStage':     {'kind': 'audio'},
    'AudioMIRStage':                {'kind': 'text'},
    'ScoreStage':                   {'kind': 'text'},
    'ScoreEditorStage':             {'kind': 'text'},
    'MidiEditorStage':              {'kind': 'audio'},
    'ScoreToMidiStage':             {'kind': 'text'},
    'SF2SynthStage':                {'kind': 'audio'},
    'ClickTrackStage':              {'kind': 'audio'},
    'ChordAccompStage':             {'kind': 'text'},
    'MuseReverbStage':              {'kind': 'audio'},
    'SlitScanStage':                {'kind': 'video'},
    'FeedbackFXStage':              {'kind': 'video'},
    'StrobeStage':                  {'kind': 'video'},
    'ExpressionStage':              {'kind': 'text'},
    'Select0rStage':                {'kind': 'video'},
    'ArtFXStage':                   {'kind': 'video'},
    'GlitchFXStage':                {'kind': 'video'},
    'KaleidoscopeStage':            {'kind': 'video'},
    'WaveWarpStage':                {'kind': 'video'},
    'WaterStage':                   {'kind': 'video'},
    'LightGraffitiStage':           {'kind': 'video'},
    'Video360StabilizeStage':       {'kind': 'video'},
    'Card3DStage':                  {'kind': 'video'},
    'STMapGenStage':                {'kind': 'image'},
    'RegrainStage':                 {'kind': 'video'},
    'ContactSheetStage':            {'kind': 'image'},
    'KenBurnsStage':                {'kind': 'video'},
    'OldFilmStage':                 {'kind': 'video'},
    'AnnotateStage':                {'kind': 'video'},
    'AudioReactiveStage':           {'kind': 'text'},
    'AudioMeterStage':              {'kind': 'video'},
    'PanoramaStage':                {'kind': 'panorama',     'workflow_kind': 'panorama'},
    'PanoramaCurrentViewStage':     {'kind': 'image',       'variant': 'transform'},
    'PanoramaMultiViewStage':       {'kind': 'image-batch', 'variant': 'transform'},
    'StoryboardStage':              {'kind': 'storyboard',   'workflow_kind': 'storyboard'},
    'TextLoaderStage':              {'kind': 'text',        'variant': 'loader'},
    'ImageLoaderStage':             {'kind': 'image',       'variant': 'loader'},
    'VideoLoaderStage':             {'kind': 'video',       'variant': 'loader'},
    'AudioLoaderStage':             {'kind': 'audio',       'variant': 'loader'},
    'AssetImageLoaderStage':        {'kind': 'image',       'variant': 'loader'},
    'AssetVideoLoaderStage':        {'kind': 'video',       'variant': 'loader'},
    'AssetAudioLoaderStage':        {'kind': 'audio',       'variant': 'loader'},
    'AssetTextLoaderStage':         {'kind': 'text',        'variant': 'loader'},
    'Scene3DStage':                 {'kind': 'image',       'variant': 'loader'},
    'LayerEditorStage':             {'kind': 'image',       'variant': 'loader'},
    'StoryboardEditorStage':        {'kind': 'image',       'variant': 'loader'},
    'MaterialStage':                {'kind': 'material',     'workflow_kind': 'material-estimate'},
    'Model3DStage':                 {'kind': 'model',        'workflow_kind': 'model'},
    'ModelLoaderStage':             {'kind': 'model',       'variant': 'loader'},
    'AssetModelLoaderStage':        {'kind': 'model',       'variant': 'loader'},
    'MeshOpStage':                  {'kind': 'model'},
    'MeshBakeMapsStage':            {'kind': 'model'},
    'MeshPrimitiveStage':           {'kind': 'model',       'variant': 'loader'},
    'MeshBooleanStage':             {'kind': 'model'},
    'LineArtStage':                 {'kind': 'image'},
    'PosterStage':                  {'kind': 'image'},
    'BlenderSceneStage':            {'kind': 'image',       'variant': 'loader'},
    'BlenderCameraStage':           {'kind': 'image'},
    'BlenderAnimationStage':        {'kind': 'video'},
}


_KIND_TO_OUTPUT_TYPE: dict[str, str] = {
    'image-batch':  'images',
    'image-picker': 'image',
    'audio-picker': 'audio',
    'video-picker': 'video',
}
